version: '3.9'

services:
  frontend:
    build: ./frontend
    command: ["sh", "-c", "npm run dev"]
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

volumes:
  data: