version: '3.9'

services:
  # frontend:
  #   build: ./frontend
  #   command: ["sh", "-c", "npm run dev"]
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./frontend:/frontend
  #     - /frontend/node_modules

  backend:
    build: backend
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend

volumes:
  data: